/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.players.view;

import com.players.view.JFInterface;
import com.model.bean.ControlePorta;
import com.model.bean.Jogadores;
import com.model.dao.JogadoresDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class ControleTemperatura extends javax.swing.JFrame {
    Jogadores tapp;
    ControlePorta cp = new ControlePorta();

    /**
     * Creates new form ControleTemperatura
     */
    public ControleTemperatura() {

    }

    public ControleTemperatura(ControlePorta cp, Jogadores tap) {
        this.cp = cp;
        this.tapp=tap;
        initComponents();
        Thread atualiza = new Thread(new ControleTemperatura.atualizaTemp());
        atualiza.start();
    }

    class atualizaTemp implements Runnable {

        @Override
        public void run() {
            while (true) {
                controle();
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblTempInterna = new javax.swing.JLabel();
        btnTempIdeal = new javax.swing.JButton();
        btnTempMin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Jogador = new javax.swing.JLabel();
        lblNomeJ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Pontuação: ");

        lblTempInterna.setText("00");

        btnTempIdeal.setText("Jogar");
        btnTempIdeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempIdealActionPerformed(evt);
            }
        });

        btnTempMin.setText("Cancelar Jogo");
        btnTempMin.setEnabled(false);
        btnTempMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempMinActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Jogador.setText("Jogador: ");

        lblNomeJ.setText("-- Nome --");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTempIdeal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Jogador)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTempInterna)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTempMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(lblNomeJ))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTempInterna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jogador)
                    .addComponent(lblNomeJ))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTempIdeal)
                    .addComponent(btnTempMin)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTempIdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempIdealActionPerformed
        setTempIdeal();
        btnTempMin.enable();
        btnTempIdeal.disable();
    }//GEN-LAST:event_btnTempIdealActionPerformed

    private void btnTempMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempMinActionPerformed
        controle();
        setTempExtMin();
        btnTempIdeal.enable();
        btnTempMin.disable();
    }//GEN-LAST:event_btnTempMinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jogador;
    private javax.swing.JButton btnTempIdeal;
    private javax.swing.JButton btnTempMin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNomeJ;
    private javax.swing.JLabel lblTempInterna;
    // End of variables declaration//GEN-END:variables

    private void setTempIdeal() {
        cp.enviaDados((int) '1');
        try {
            Thread.sleep(20);
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Thread.sleep(20);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setTempExtMin() {
        cp.enviaDados((int) '2');
        try {
            Thread.sleep(20);
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Thread.sleep(20);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
Integer antigo=0;
    private void controle() {
        Integer novo = cp.recebeDados();
        if (novo != -1) {
            if(novo < 200){
            lblTempInterna.setText(Integer.toString(novo));
            lblNomeJ.setText(tapp.getNome());
            }
            else
            {     
            JogadoresDAO vdao = new JogadoresDAO();
            tapp.setPontuacao(antigo);
            vdao.update(tapp);
                JOptionPane.showMessageDialog(null, "Obrigado por jogar, pontuação final: " + antigo);
                dispose();
            }
        }
        antigo = novo;
    }
    
    
}